In [1]:
!pip install tensorflow --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 44.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 64.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 38.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 15.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 18.6 MB/s eta 0:00:00
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtypes-0.2.0:
      Successfully uninstalled ml-dtypes-0.2.0
  Attempting uninstall: h5py
    Found existing installation: h5py 3.9.0
    Uninstalling h5py-3.9.0:
      Successfully uninstalled h5py-3.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.15.2
    Uninstalling tensorboard-2.15.2:
      Successfully uninstalled tensorboard-2.15.2
  Attempting uninstall: keras
    Fo

In [2]:
import tensorflow as tf
import pandas as pd
import pickle
import os
import matplotlib.pyplot as plt


In [3]:
def generate_dataset(annotations, image_dir):

    with open('/content/drive/MyDrive/Astronomodel/annotations.pkl', 'rb') as handle:
        annotations = pickle.load(handle)

    df = pd.DataFrame.from_dict(annotations, orient='index')
    df.reset_index(inplace = True, drop = False)
    df.columns = ["id", "caption"]
    df = df.astype({'id': 'int', 'caption': 'string'})
    df_dict = df.to_dict(orient='list')


    dataset = tf.data.Dataset.from_tensor_slices(df_dict)
    return dataset

In [4]:
dataset = generate_dataset(_, _)
print(next(iter(dataset)))

{'id': <tf.Tensor: shape=(), dtype=int32, numpy=240423>, 'caption': <tf.Tensor: shape=(), dtype=string, numpy=b"What created this giant X in the clouds? It was the shadow of contrails. When airplanes fly, humid engine exhaust may form water droplets that might freeze in Earth's cold upper atmosphere. These persistent streams of water and ice scatter light from the Sun above and so appear bright. These contrails cast long shadows. That was just the case over Istanbul, T\xc3\xbcrkiye, earlier this month. Contrails occur all over planet Earth and, generally, warm the Earth when the trap infrared light but cool the Earth when they efficiently reflect sunlight. The image was taken by a surprised photographer in the morning on the way to work.">}


In [5]:
print(len(dataset))

9536


In [6]:
list_ds = tf.data.Dataset.list_files("/content/drive/MyDrive/Astronomodel/Images/*")

In [11]:
print(next(iter(list_ds)))

tf.Tensor(b'/content/drive/MyDrive/Astronomodel/Images/000518.png', shape=(), dtype=string)


In [13]:
# Reads an image from a file, decodes it into a dense tensor, and resizes it
# to a fixed shape.
#def parse_image(filename):
#  parts = tf.strings.split(filename, os.sep)
#  label = parts[-2]


#  image = tf.image.resize(image, [1024, 1024])
#  return image, label

#def _parse_function(filename):
#    filename = tf.strings.split(filename, os.sep).values
#    print(filename)
#    image = tf.io.read_file(filename)
#    image = tf.io.decode_png(image)
#    image = tf.image.convert_image_dtype(image, tf.float32)
#    return image

#image_ds = list_ds.map(_parse_function)

In [31]:
# step 1
raw_filenames = os.listdir("/content/drive/MyDrive/Astronomodel/Images/")
file_paths = ["/content/drive/MyDrive/Astronomodel/Images/" + x for x in raw_filenames]
filenames = tf.constant(file_paths) #['im_01.jpg', 'im_02.jpg', 'im_03.jpg', 'im_04.jpg'])
# labels = tf.constant([0, 1, 0, 1])
#print(filenames)

# step 2: create a dataset returning slices of `filenames`
dataset = tf.data.Dataset.from_tensor_slices((filenames))

# step 3: parse every image in the dataset using `map`
def _parse_function(filename): #, label):
    image_string = tf.io.read_file(filename)
    image_decoded = tf.io.decode_png(image_string)
    image = tf.cast(image_decoded, tf.float32)
    return image #, label

image_dataset = dataset.map(_parse_function)

In [32]:
print(image_dataset)
print(next(iter(image_dataset)))

<_MapDataset element_spec=TensorSpec(shape=(None, None, None), dtype=tf.float32, name=None)>
tf.Tensor(
[[[  4.   0.   0.]
  [ 25.  13.  22.]
  [136. 135. 128.]
  ...
  [  3.  12.   0.]
  [  8.  10.   3.]
  [ 17.  14.   1.]]

 [[  8.   3.   1.]
  [ 23.  14.   7.]
  [ 66.  59.  48.]
  ...
  [ 34.  56.  21.]
  [  9.   9.   1.]
  [ 17.   9.   0.]]

 [[  8.   1.   0.]
  [ 12.   5.   0.]
  [ 20.  15.   4.]
  ...
  [ 62.  62.  23.]
  [  2.   7.   8.]
  [ 20.  36.  28.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]], shape=(1024, 1024, 3), dtype=float32)


In [30]:
file_path = next(iter(list_ds))
image, label = parse_image(file_path)

def show(image, label):
  plt.figure()
  plt.imshow(image)
  plt.title(label.numpy().decode('utf-8'))
  plt.axis('off')

show(image, label)


NameError: name 'parse_image' is not defined